### ISSUE TITLE
The SSL certificate is outdated

### ISSUE THREAD

**Issue by iaeiou** [aardrian/DoesYourSiteDeserveRecognition.com#1]

**Comment by BogdanCerovac** [comment]
@aardrian - seems like R3 issued certificate expired 10/6/2021. If it's possible - I suggest using https://letsencrypt.org to avoid future problems (provided hosting supports it - if not I can offer a part of my shared host).

**Comment by aardrian** [comment]
Fixed. I have no idea why I missed this notification months ago.

The Let's Encrypt (which is the cert it had before) cert expired and did not auto-renew.
